{
  "formatVersion": "1.1",
  "component": {
    "group": "net.minecraftforge",
    "module": "fmlloader",
    "version": "1.18.2-40.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forgespi",
          "version": {
            "requires": "4.0.15-4.x"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "21.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.6.4"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.4"
          }
        },
        {
          "group": "cpw.mods",
          "module": "modlauncher",
          "version": {
            "requires": "9.0.+"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "coremods",
          "version": {
            "requires": "5.0.+"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "JarJar",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "fmlloader-1.18.2-40.2.0.jar",
          "url": "fmlloader-1.18.2-40.2.0.jar",
          "size": 256614,
          "sha512": "7d3a4820cbecfddff2d38d5885fc7141a43cae11edfc9333e89794828be42d5c3577fc2f93e7163ffee91d9de5dd1d59afc428941341137ea21e24da1934a6d5",
          "sha256": "c7433ca8a23a05bcc326ed83795820f5b0828e294d8e771a83687b9c3ba8ce3f",
          "sha1": "1166c0df109ded579c9b9c84c81c814aa51f2949",
          "md5": "6aef0cbe8519d14c4b028a41807e6bb2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        },
        {
          "group": "cpw.mods",
          "module": "securejarhandler",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "accesstransformers",
          "version": {
            "requires": "8.0.4"
          }
        },
        {
          "group": "net.minecrell",
          "module": "terminalconsoleappender",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forgespi",
          "version": {
            "requires": "4.0.15-4.x"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "21.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.6.4"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.4"
          }
        },
        {
          "group": "cpw.mods",
          "module": "modlauncher",
          "version": {
            "requires": "9.0.+"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "coremods",
          "version": {
            "requires": "5.0.+"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "JarJar",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "fmlloader-1.18.2-40.2.0.jar",
          "url": "fmlloader-1.18.2-40.2.0.jar",
          "size": 256614,
          "sha512": "7d3a4820cbecfddff2d38d5885fc7141a43cae11edfc9333e89794828be42d5c3577fc2f93e7163ffee91d9de5dd1d59afc428941341137ea21e24da1934a6d5",
          "sha256": "c7433ca8a23a05bcc326ed83795820f5b0828e294d8e771a83687b9c3ba8ce3f",
          "sha1": "1166c0df109ded579c9b9c84c81c814aa51f2949",
          "md5": "6aef0cbe8519d14c4b028a41807e6bb2"
        }
      ]
    }
  ]
}
