{
  "formatVersion": "1.1",
  "component": {
    "group": "net.minecraftforge",
    "module": "JarJar",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.0.1-jre"
          }
        },
        {
          "group": "com.machinezoo.noexception",
          "module": "noexception",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "JarJar-0.3.0.jar",
          "url": "JarJar-0.3.0.jar",
          "size": 60569,
          "sha512": "e850b2323c32db5397491fdf673c3013a1957ea999c16c02599cce59a2c1b55b024c968da6a215f1fe35c2b8eac3050d543bc1b67992e40f0599dbd0f6e721b6",
          "sha256": "f60e1761055ffae591e8087b8c303a544da34140f27c2e891df715228d5a30d0",
          "sha1": "224dc7851fd1613b681365adcd8af636aa52e505",
          "md5": "7733c150d5aa87caf75c34618d116619"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.0.1-jre"
          }
        },
        {
          "group": "com.machinezoo.noexception",
          "module": "noexception",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "JarJar-0.3.0.jar",
          "url": "JarJar-0.3.0.jar",
          "size": 60569,
          "sha512": "e850b2323c32db5397491fdf673c3013a1957ea999c16c02599cce59a2c1b55b024c968da6a215f1fe35c2b8eac3050d543bc1b67992e40f0599dbd0f6e721b6",
          "sha256": "f60e1761055ffae591e8087b8c303a544da34140f27c2e891df715228d5a30d0",
          "sha1": "224dc7851fd1613b681365adcd8af636aa52e505",
          "md5": "7733c150d5aa87caf75c34618d116619"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "JarJar-0.3.0-sources.jar",
          "url": "JarJar-0.3.0-sources.jar",
          "size": 24855,
          "sha512": "03139fd7aeef605cbf6e165bbe66ebf3927c881a5b7bdfd732a0a84d8a8e47ac887fe77aabee7a6677a828a4ea40380b63bf65e001ae85f5e24cb2fa3c20a986",
          "sha256": "64f4620acabd42f19b67f3fc2b072ccc95a9353a3fa5414b14ad1b1c19f5a9d3",
          "sha1": "d5ee530cc88374e2e2c84a7f123faf39c12930fd",
          "md5": "3cd651fdd5b9121ac1bce715d734e869"
        }
      ]
    }
  ]
}
