{
  "formatVersion": "1.1",
  "component": {
    "group": "cpw.mods",
    "module": "securejarhandler",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        }
      ],
      "files": [
        {
          "name": "securejarhandler-1.0.3.jar",
          "url": "securejarhandler-1.0.3.jar",
          "size": 103266,
          "sha512": "1a3e89df6c32d19515b74f936fb258271af5fcd915a33ce93367600a85a9341fe847d4fdffe564bbfaf7e6f967fd2ff1a41e9d66ceb7dfb3883a6fb754f32707",
          "sha256": "fac5c48708626a8660b3599d3567852dad72d53ddc49ac922a809e00f967d6d5",
          "sha1": "acbf5e3c8a38fb8bf824a54fe45eee121c510392",
          "md5": "678ec8927eb25f596db7e620a716befc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        }
      ],
      "files": [
        {
          "name": "securejarhandler-1.0.3.jar",
          "url": "securejarhandler-1.0.3.jar",
          "size": 103266,
          "sha512": "1a3e89df6c32d19515b74f936fb258271af5fcd915a33ce93367600a85a9341fe847d4fdffe564bbfaf7e6f967fd2ff1a41e9d66ceb7dfb3883a6fb754f32707",
          "sha256": "fac5c48708626a8660b3599d3567852dad72d53ddc49ac922a809e00f967d6d5",
          "sha1": "acbf5e3c8a38fb8bf824a54fe45eee121c510392",
          "md5": "678ec8927eb25f596db7e620a716befc"
        }
      ]
    }
  ]
}
