{
  "formatVersion": "1.1",
  "component": {
    "group": "net.minecraftforge",
    "module": "javafmllanguage",
    "version": "1.18.2-40.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "javafmllanguage-1.18.2-40.2.0.jar",
          "url": "javafmllanguage-1.18.2-40.2.0.jar",
          "size": 16290,
          "sha512": "261c2c7948bdc995bd49ccc131b716681b5c071c2b00f7f4e3a2000167dbcbe182d1eecc7c4af8aad6461d40e5b0172acab89776a48966faa8d984c2bd169d44",
          "sha256": "7f03c6bf7c0dec61ee9fed43530b9de899f9634a17620be67f25558c8f965905",
          "sha1": "852eaf68007f6a5469e0887b7d08b2774b383cd6",
          "md5": "281dd7df35136397ee7a1d90c2d7b7b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "fmlloader",
          "version": {
            "requires": "1.18.2-40.2.0"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "fmlcore",
          "version": {
            "requires": "1.18.2-40.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "javafmllanguage-1.18.2-40.2.0.jar",
          "url": "javafmllanguage-1.18.2-40.2.0.jar",
          "size": 16290,
          "sha512": "261c2c7948bdc995bd49ccc131b716681b5c071c2b00f7f4e3a2000167dbcbe182d1eecc7c4af8aad6461d40e5b0172acab89776a48966faa8d984c2bd169d44",
          "sha256": "7f03c6bf7c0dec61ee9fed43530b9de899f9634a17620be67f25558c8f965905",
          "sha1": "852eaf68007f6a5469e0887b7d08b2774b383cd6",
          "md5": "281dd7df35136397ee7a1d90c2d7b7b3"
        }
      ]
    }
  ]
}
