{
  "formatVersion": "1.1",
  "component": {
    "group": "net.minecraftforge",
    "module": "fmlcore",
    "version": "1.18.2-40.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "eventbus",
          "version": {
            "requires": "5.0.+"
          }
        }
      ],
      "files": [
        {
          "name": "fmlcore-1.18.2-40.2.0.jar",
          "url": "fmlcore-1.18.2-40.2.0.jar",
          "size": 109981,
          "sha512": "92259fab0e881dba24b64ac48bfeaf15311e50b9c2d39ec25df06d954dc1aa2233089997b4dd35298ee18b8560fb197da94c03f56344d6e75d8fffd9ae021009",
          "sha256": "45d4462447ea50c19351436fad966618335adabb54a844cfe9bb6602bfc4365c",
          "sha1": "4f2c9b9eb2817afedcc4b5460d9ee7b185184ed4",
          "md5": "a8a078095bb99f6358db4d6bed8eaf85"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "fmlloader",
          "version": {
            "requires": "1.18.2-40.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "eventbus",
          "version": {
            "requires": "5.0.+"
          }
        }
      ],
      "files": [
        {
          "name": "fmlcore-1.18.2-40.2.0.jar",
          "url": "fmlcore-1.18.2-40.2.0.jar",
          "size": 109981,
          "sha512": "92259fab0e881dba24b64ac48bfeaf15311e50b9c2d39ec25df06d954dc1aa2233089997b4dd35298ee18b8560fb197da94c03f56344d6e75d8fffd9ae021009",
          "sha256": "45d4462447ea50c19351436fad966618335adabb54a844cfe9bb6602bfc4365c",
          "sha1": "4f2c9b9eb2817afedcc4b5460d9ee7b185184ed4",
          "md5": "a8a078095bb99f6358db4d6bed8eaf85"
        }
      ]
    }
  ]
}
