{
  "formatVersion": "1.1",
  "component": {
    "group": "net.minecraftforge",
    "module": "mclanguage",
    "version": "1.18.2-40.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mclanguage-1.18.2-40.2.0.jar",
          "url": "mclanguage-1.18.2-40.2.0.jar",
          "size": 4984,
          "sha512": "1bb8ce83535ec21e37bd844a193e8fb6246ad8ae0d5c536f9dea477208e23b68aee20e1968984c72a2a55211137cfb2d364b7e3f803ecaec5252c97aa3aec8dc",
          "sha256": "89bf383d89e9551ee701328e6d6a2905673679f79d8a426cb8a8f74544954315",
          "sha1": "3674996268700c2d8653900d9286b793adde14c4",
          "md5": "f7af9eb3036d58dad5d5b97571888a8f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "fmlloader",
          "version": {
            "requires": "1.18.2-40.2.0"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "fmlcore",
          "version": {
            "requires": "1.18.2-40.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "mclanguage-1.18.2-40.2.0.jar",
          "url": "mclanguage-1.18.2-40.2.0.jar",
          "size": 4984,
          "sha512": "1bb8ce83535ec21e37bd844a193e8fb6246ad8ae0d5c536f9dea477208e23b68aee20e1968984c72a2a55211137cfb2d364b7e3f803ecaec5252c97aa3aec8dc",
          "sha256": "89bf383d89e9551ee701328e6d6a2905673679f79d8a426cb8a8f74544954315",
          "sha1": "3674996268700c2d8653900d9286b793adde14c4",
          "md5": "f7af9eb3036d58dad5d5b97571888a8f"
        }
      ]
    }
  ]
}
