{
  "formatVersion": "1.1",
  "component": {
    "group": "net.jodah",
    "module": "typetools",
    "version": "0.8.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "gvfiencxc5gdfb7eoqfdq2lqcy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "typetools-0.8.3.jar",
          "url": "typetools-0.8.3.jar",
          "size": 15425,
          "sha512": "1ddfde3a9d15c064cc7e4372daed5155e69253df0c1bc5172e689567e66bfd426ff2db5404c5acabac758f7cd14b0be3f9f401c44ad9de56b6d80f784815c154",
          "sha256": "f853e21f7de6bd192f0ce09e64a6c8b0e154c9cf9f34e62f08d5e26f73ce3b19",
          "sha1": "98f84f353457629e81cc6827224871b1a8faa7af",
          "md5": "ee4596e1413cc1a5e080c971d6064753"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "typetools-0.8.3.jar",
          "url": "typetools-0.8.3.jar",
          "size": 15425,
          "sha512": "1ddfde3a9d15c064cc7e4372daed5155e69253df0c1bc5172e689567e66bfd426ff2db5404c5acabac758f7cd14b0be3f9f401c44ad9de56b6d80f784815c154",
          "sha256": "f853e21f7de6bd192f0ce09e64a6c8b0e154c9cf9f34e62f08d5e26f73ce3b19",
          "sha1": "98f84f353457629e81cc6827224871b1a8faa7af",
          "md5": "ee4596e1413cc1a5e080c971d6064753"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "typetools-0.8.3-javadoc.jar",
          "url": "typetools-0.8.3-javadoc.jar",
          "size": 22831,
          "sha512": "1a0e35eba05f42ce903648445bcf98fb876d3c932da5f33b748ca8811fcb34f3ddb2d7e1c86f2d6aae90c94c6021264422804e040b2b24b2692151597275cde8",
          "sha256": "50a6d260bf032f383d210a01e283538b58e900a8bdc1ddea333abcea1af4fa40",
          "sha1": "86df6f268f68dc2182a593c26e8cd03f424ef6b2",
          "md5": "8d7b398056076113652c1d149e4ef1c7"
        }
      ]
    }
  ]
}
